-- =====================================================================
-- Mika Creator — migration 001: votes v1 -> v2
-- Generated by scripts/generate/vote-migration.mjs
-- Maps 169 legacy record_keys ("<Category>|<index>") to new
-- object_type='asset' + object_id=<slug>, preserving every historical vote.
--
-- HOW TO RUN (EXISTING v1 project): Dashboard -> SQL Editor -> paste + Run.
-- Afterwards run the (idempotent) parts of supabase/schema.sql for the v2
-- RPCs/comments table — that file is safe to execute against this state.
-- =====================================================================

begin;

-- 1) new columns
alter table public.votes add column if not exists object_type text;
alter table public.votes add column if not exists object_id   text;

-- 2) mapping table
create temp table _legacy_vote_map (
  record_key  text primary key,
  object_type text,
  object_id   text
) on commit drop;
insert into _legacy_vote_map (record_key, object_type, object_id) values
  ('Farm|0', 'asset', 'farm-img-20260607-085012'),
  ('Farm|1', 'asset', 'farm-img-20260607-085413'),
  ('Girl on Girl|0', 'asset', 'girl-on-girl-whatsapp-image-2026-08-24-at-09-14-32'),
  ('Girl on Girl|1', 'asset', 'girl-on-girl-whatsapp-image-2026-08-24-at-09-14-33-1'),
  ('Girl on Girl|2', 'asset', 'girl-on-girl-whatsapp-image-2026-08-24-at-09-14-33-2'),
  ('Girl on Girl|3', 'asset', 'girl-on-girl-whatsapp-image-2026-08-24-at-09-14-33'),
  ('Girl on Girl|4', 'asset', 'girl-on-girl-whatsapp-image-2026-08-24-at-09-14-34'),
  ('Girl on Girl|5', 'asset', 'girl-on-girl-whatsapp-image-2026-08-24-at-09-14-36-1'),
  ('Girl on Girl|6', 'asset', 'girl-on-girl-whatsapp-image-2026-08-24-at-09-14-36'),
  ('Girl on Girl|7', 'asset', 'girl-on-girl-whatsapp-image-2026-08-24-at-09-14-37'),
  ('Hotels|0', 'asset', 'indoor-img-20260521-152726'),
  ('Hotels|1', 'asset', 'indoor-img-20260521-152935'),
  ('Hotels|2', 'asset', 'indoor-img-20260521-152938'),
  ('Hotels|3', 'asset', 'indoor-img-20260521-153005'),
  ('Hotels|4', 'asset', 'hotels-img-20260521-153241'),
  ('Hotels|5', 'asset', 'hotels-img-20260521-153246'),
  ('Hotels|6', 'asset', 'hotels-img-20260521-153301'),
  ('Hotels|7', 'asset', 'hotels-img-20260604-151045'),
  ('Hotels|8', 'asset', 'hotels-img-20260604-151110'),
  ('Hotels|9', 'asset', 'hotels-img-20260604-151145'),
  ('Hotels|10', 'asset', 'hotels-img-20260604-151154'),
  ('Hotels|11', 'asset', 'hotels-img-20260604-151223'),
  ('Hotels|12', 'asset', 'hotels-img-20260604-151407'),
  ('Hotels|13', 'asset', 'hotels-img-20260604-151536'),
  ('Hotels|14', 'asset', 'hotels-img-20260604-151707'),
  ('Hotels|15', 'asset', 'hotels-img-20260605-180923'),
  ('Hotels|16', 'asset', 'hotels-img-20260605-181052'),
  ('Hotels|17', 'asset', 'hotels-img-20260605-181055'),
  ('Hotels|18', 'asset', 'hotels-img-20260605-181118'),
  ('Hotels|19', 'asset', 'hotels-img-20260605-181121'),
  ('Hotels|20', 'asset', 'hotels-img-20260605-181126'),
  ('Hotels|21', 'asset', 'hotels-img-20260605-181131'),
  ('Hotels|22', 'asset', 'hotels-img-20260605-181138'),
  ('Hotels|23', 'asset', 'hotels-img-20260605-181144'),
  ('Hotels|24', 'asset', 'hotels-img-20260605-184128'),
  ('Hotels|25', 'asset', 'hotels-img-20260605-184146'),
  ('Hotels|26', 'asset', 'hotels-img-20260605-184252'),
  ('Hotels|27', 'asset', 'hotels-img-20260605-184257'),
  ('Hotels|28', 'asset', 'hotels-img-20260605-184305'),
  ('Hotels|29', 'asset', 'hotels-img-20260605-184324'),
  ('Hotels|30', 'asset', 'hotels-img-20260605-184333'),
  ('Hotels|31', 'asset', 'hotels-img-20260605-184346'),
  ('Hotels|32', 'asset', 'hotels-img-20260605-184350'),
  ('Hotels|33', 'asset', 'hotels-img-20260605-184359'),
  ('Hotels|34', 'asset', 'hotels-img-20260605-184619'),
  ('Hotels|35', 'asset', 'hotels-img-20260605-184622'),
  ('Hotels|36', 'asset', 'hotels-img-20260605-184743'),
  ('Hotels|37', 'asset', 'hotels-img-20260605-184749'),
  ('Hotels|38', 'asset', 'hotels-img-20260605-184754'),
  ('Hotels|39', 'asset', 'hotels-img-20260605-184905'),
  ('Indoor|0', 'asset', 'indoor-img-20260521-152614'),
  ('Indoor|1', 'asset', 'indoor-img-20260521-152632'),
  ('Indoor|2', 'asset', 'indoor-img-20260521-152704'),
  ('Indoor|3', 'asset', 'indoor-img-20260521-152717'),
  ('Indoor|4', 'asset', 'indoor-img-20260521-152726'),
  ('Indoor|5', 'asset', 'indoor-img-20260521-152748'),
  ('Indoor|6', 'asset', 'indoor-img-20260521-152753'),
  ('Indoor|7', 'asset', 'indoor-img-20260521-152819-burst002'),
  ('Indoor|8', 'asset', 'indoor-img-20260521-152821'),
  ('Indoor|9', 'asset', 'indoor-img-20260521-152911'),
  ('Indoor|10', 'asset', 'indoor-img-20260521-152923'),
  ('Indoor|11', 'asset', 'indoor-img-20260521-152935'),
  ('Indoor|12', 'asset', 'indoor-img-20260521-152938'),
  ('Indoor|13', 'asset', 'indoor-img-20260521-153005'),
  ('Mika River|0', 'asset', 'mika-river-img-20260702-150053'),
  ('Mika River|1', 'asset', 'mika-river-img-20260702-150109'),
  ('Mika River|2', 'asset', 'mika-river-img-20260702-150121'),
  ('Mika River|3', 'asset', 'mika-river-img-20260702-150129'),
  ('Mika River|4', 'asset', 'mika-river-img-20260702-150152'),
  ('Mika River|5', 'asset', 'mika-river-img-20260702-150158'),
  ('Mika River|6', 'asset', 'mika-river-img-20260702-150201'),
  ('Mika River|7', 'asset', 'mika-river-img-20260702-150228'),
  ('Mika River|8', 'asset', 'mika-river-img-20260702-150239'),
  ('Mika River|9', 'asset', 'mika-river-img-20260702-150324'),
  ('Mika River|10', 'asset', 'mika-river-img-20260702-150357'),
  ('Mika River|11', 'asset', 'mika-river-img-20260702-150402'),
  ('Mika River|12', 'asset', 'mika-river-img-20260702-150405'),
  ('Mika River|13', 'asset', 'mika-river-img-20260702-150421'),
  ('Mika River|14', 'asset', 'mika-river-img-20260702-150439'),
  ('Mika River|15', 'asset', 'mika-river-img-20260702-150509'),
  ('Mika River|16', 'asset', 'mika-river-img-20260702-150520'),
  ('Mika River|17', 'asset', 'mika-river-img-20260702-150820'),
  ('Mika River|18', 'asset', 'mika-river-img-20260702-150826'),
  ('Mika River|19', 'asset', 'mika-river-img-20260702-150832'),
  ('Mika River|20', 'asset', 'mika-river-img-20260702-150838'),
  ('Mika River|21', 'asset', 'mika-river-img-20260702-150844'),
  ('Mika River|22', 'asset', 'mika-river-img-20260702-150852'),
  ('Mika River|23', 'asset', 'mika-river-img-20260702-150908'),
  ('Mika River|24', 'asset', 'mika-river-img-20260702-150933'),
  ('Mika River|25', 'asset', 'mika-river-img-20260702-150942'),
  ('Mika River|26', 'asset', 'mika-river-img-20260702-151011'),
  ('Mika River|27', 'asset', 'mika-river-img-20260702-151021'),
  ('Mika River|28', 'asset', 'mika-river-img-20260702-151120'),
  ('Mika River|29', 'asset', 'mika-river-img-20260702-151136'),
  ('Mika River|30', 'asset', 'mika-river-img-20260702-151159'),
  ('Mika River|31', 'asset', 'mika-river-img-20260702-151205'),
  ('Mika River|32', 'asset', 'mika-river-img-20260702-151217'),
  ('Mika River|33', 'asset', 'mika-river-img-20260702-151220'),
  ('Mika River|34', 'asset', 'mika-river-img-20260702-151419'),
  ('Mika River|35', 'asset', 'mika-river-img-20260702-151639'),
  ('Mika River|36', 'asset', 'mika-river-img-20260702-151647'),
  ('Mika River|37', 'asset', 'mika-river-img-20260702-151708'),
  ('Mika River|38', 'asset', 'mika-river-img-20260702-151710'),
  ('Mika River|39', 'asset', 'mika-river-img-20260702-151714'),
  ('Mika River|40', 'asset', 'mika-river-img-20260702-151749'),
  ('Mika River|41', 'asset', 'mika-river-img-20260702-151753'),
  ('Mika River|42', 'asset', 'mika-river-img-20260702-154157'),
  ('Mika River|43', 'asset', 'mika-river-img-20260702-154201'),
  ('Mika River|44', 'asset', 'mika-river-img-20260702-154205'),
  ('Mika River|45', 'asset', 'mika-river-img-20260702-154217'),
  ('Mika River|46', 'asset', 'mika-river-img-20260702-154226'),
  ('Mika River|47', 'asset', 'mika-river-img-20260702-154236'),
  ('Mika River|48', 'asset', 'mika-river-img-20260702-154256'),
  ('Mika River|49', 'asset', 'mika-river-img-20260702-154319'),
  ('Mika River|50', 'asset', 'mika-river-img-20260702-154327'),
  ('Mika River|51', 'asset', 'mika-river-img-20260702-154331'),
  ('Mika River|52', 'asset', 'mika-river-img-20260702-154350'),
  ('Mountain|0', 'asset', 'mountain-img-20260609-112339'),
  ('Mountain|1', 'asset', 'mountain-img-20260609-112344'),
  ('Mountain|2', 'asset', 'mountain-img-20260609-112346'),
  ('Mountain|3', 'asset', 'mountain-img-20260609-112406'),
  ('Mountain|4', 'asset', 'mountain-img-20260609-112408'),
  ('Mountain|5', 'asset', 'mountain-img-20260609-112414'),
  ('Mountain|6', 'asset', 'mountain-img-20260609-112416'),
  ('Mountain|7', 'asset', 'mountain-img-20260609-112427'),
  ('Mountain|8', 'asset', 'mountain-img-20260609-112429'),
  ('Mountain|9', 'asset', 'mountain-img-20260609-112432'),
  ('Mountain|10', 'asset', 'mountain-img-20260609-113438'),
  ('Mountain|11', 'asset', 'mountain-img-20260609-113441'),
  ('Mountain|12', 'asset', 'mountain-img-20260609-113447'),
  ('Mountain|13', 'asset', 'mountain-img-20260609-113455'),
  ('Mountain|14', 'asset', 'mountain-img-20260609-113458'),
  ('Mountain|15', 'asset', 'mountain-img-20260609-113502'),
  ('Mountain|16', 'asset', 'mountain-img-20260609-113506'),
  ('Mountain|17', 'asset', 'mountain-img-20260609-113508'),
  ('Mountain|18', 'asset', 'mountain-img-20260609-113519'),
  ('Mountain|19', 'asset', 'mountain-img-20260609-113525'),
  ('Mountain|20', 'asset', 'mountain-img-20260609-113526'),
  ('Mountain|21', 'asset', 'mountain-img-20260609-113529'),
  ('Mountain|22', 'asset', 'mountain-img-20260609-113532'),
  ('Mountain|23', 'asset', 'mountain-img-20260609-113533'),
  ('Mountain|24', 'asset', 'mountain-img-20260609-113537'),
  ('Mountain|25', 'asset', 'mountain-img-20260609-113544'),
  ('Mountain|26', 'asset', 'mountain-img-20260609-113546'),
  ('Mountain|27', 'asset', 'mountain-img-20260609-113553'),
  ('Mountain|28', 'asset', 'mountain-img-20260609-113556'),
  ('Mountain|29', 'asset', 'mountain-img-20260609-153136'),
  ('Mountain|30', 'asset', 'mountain-img-20260609-153137'),
  ('Mountain|31', 'asset', 'mountain-img-20260609-153147'),
  ('Mountain|32', 'asset', 'mountain-whatsapp-image-2026-08-24-at-09-14-37-1'),
  ('Mountain|33', 'asset', 'mountain-whatsapp-image-2026-08-24-at-09-14-37-2'),
  ('Mountain|34', 'asset', 'mountain-whatsapp-image-2026-08-24-at-09-14-38'),
  ('Mountain|35', 'asset', 'mountain-img-20260609-123301'),
  ('Mountain|36', 'asset', 'mountain-img-20260609-123312'),
  ('Mountain|37', 'asset', 'mountain-img-20260609-123316'),
  ('Mountain|38', 'asset', 'mountain-img-20260609-123319'),
  ('Mountain|39', 'asset', 'mountain-img-20260609-125630'),
  ('Mountain|40', 'asset', 'mountain-img-20260609-125632'),
  ('Mountain|41', 'asset', 'mountain-img-20260609-153230'),
  ('Mountain|42', 'asset', 'mountain-img-20260609-153233'),
  ('Mountain|43', 'asset', 'mountain-img-20260609-153237'),
  ('Mountain|44', 'asset', 'mountain-img-20260609-153241'),
  ('Waterpark|0', 'asset', 'waterpark-img-20260607-161245'),
  ('Waterpark|1', 'asset', 'waterpark-img-20260607-161247'),
  ('Waterpark|2', 'asset', 'waterpark-img-20260607-161251'),
  ('Waterpark|3', 'asset', 'waterpark-img-20260607-161254'),
  ('Waterpark|4', 'asset', 'waterpark-img-20260607-161941'),
  ('Waterpark|5', 'asset', 'waterpark-img-20260607-162034'),
  ('Waterpark|6', 'asset', 'waterpark-img-20260607-162042');

-- 3) backfill (actions preserved; like+switch semantics unchanged)
update public.votes v
set object_type = m.object_type,
    object_id   = m.object_id
from _legacy_vote_map m
where v.record_key = m.record_key;

-- 4) votes pointing at content that no longer exists are dropped
delete from public.votes
where object_id is null or object_type is null;

-- 5) enforce the v2 "one row per visitor per object per action" shape
delete from public.votes a
using public.votes b
where a.id > b.id
  and a.object_type = b.object_type
  and a.object_id   = b.object_id
  and a.action      = b.action
  and a.voter_id    = b.voter_id;

-- 6) drop the legacy record_key column and its indexes/constraints
alter table public.votes drop constraint if exists votes_record_voter_unique;
alter table public.votes drop constraint if exists votes_record_key_key;
drop index if exists public.votes_record_idx;
alter table public.votes drop column if exists record_key;

-- 7) v2 uniqueness + indexes
alter table public.votes drop constraint if exists votes_object_voter_unique;
alter table public.votes add constraint votes_object_voter_unique
  unique (object_type, object_id, action, voter_id);
create index if not exists votes_object_idx on public.votes (object_type, object_id);
create index if not exists votes_voter_idx   on public.votes (voter_id);

-- 8) privacy shift: anon can no longer SELECT raw votes
alter table public.votes enable row level security;
revoke select on public.votes from anon, authenticated;

create or replace view public.vote_counts as
select object_type, object_id,
       count(*) filter (where action = 'like')    as likes,
       count(*) filter (where action = 'dislike') as dislikes
from public.votes group by object_type, object_id;
grant select on public.vote_counts to anon, authenticated;

commit;
